title: New Hampshire Law Enforcement Resources
description: A repository of templates for use by New Hampshire Law Enforcement and Investigators.
theme: just-the-docs

url: https://resources.iotdetective.net

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
