title: New Hampshire Law Enforcement Resources
description: A repository of templates for use by New Hampshire Law Enforcement and Investigators.
theme: just-the-docs

url: https://resources.iotdetective.net

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
